
import type { Product } from './types';

export const initialProductsData: Product[] = [
  {
    id: '1',
    name: 'Doce de Banana Cremoso Tradicional',
    description: 'O clássico doce de banana cremoso, feito com bananas maduras e um toque de carinho.',
    price: 15.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'banana sweet',
    stock: 100,
    category: 'Tradicional',
  },
  {
    id: '2',
    name: 'Doce de Banana em Barra',
    description: 'Delicioso doce de banana em barra, perfeito para um lanche rápido e energético.',
    price: 12.50,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'banana candy',
    stock: 80,
    category: 'Barra',
  },
  {
    id: '3',
    name: 'Doce de Banana com Chocolate',
    description: 'Uma combinação irresistível de doce de banana cremoso com cobertura de chocolate.',
    price: 18.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'chocolate banana',
    stock: 60,
    category: 'Especial',
  },
  {
    id: '4',
    name: 'Doce de Banana Diet',
    description: 'Saboroso doce de banana sem adição de açúcar, para quem busca uma opção mais leve.',
    price: 16.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'healthy banana',
    stock: 40,
    category: 'Diet',
  },
  {
    id: '5',
    name: 'Geleia de Banana Artesanal',
    description: 'Geleia de banana caseira, perfeita para acompanhar pães, torradas e queijos.',
    price: 20.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'banana jam',
    stock: 50,
    category: 'Geleia',
  },
  {
    id: '6',
    name: 'Bananada Cascão Crocante',
    description: 'Tradicional bananada cascão com uma textura deliciosamente crocante por fora e macia por dentro.',
    price: 14.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'crispy banana',
    stock: 70,
    category: 'Tradicional',
  },
];
