
export interface Product {
  id: string;
  name: string;
  description?: string;
  price: number; // Selling price
  imageUrl: string;
  stock: number;
  category: string;
  dataAiHint?: string;
}

export interface Promotion {
  promotionMessage: string;
  discountedProductId?: string;
  discountPercentage?: number;
}

export interface EntryFormValues {
  date: Date;
  supplier: string;
  productId: string;
  quantity: number;
  unitPrice: number; // Represents the cost per unit (Custo Unitário)
}

export interface Entry extends EntryFormValues {
  id: string;
  totalValue: number; // Represents total cost (quantity * unitPrice)
  productName?: string;
}

export interface SaleFormValues {
  date: Date;
  customer: string;
  productId: string;
  quantity: number;
  unitPrice: number; // Represents the selling price per unit (Preço de Venda Unitário)
  discount: number;
}

export interface Sale extends SaleFormValues {
  id: string;
  totalValue: number; // Represents total revenue for this sale ((quantity * unitPrice) - discount)
  productName?: string;
}

// Used internally in RelatoriosPage for aggregation and initial mapping during data processing
export interface ProductAnalysisData {
  productId: string;
  productName: string;        // Product name
  unitsSold: number;          // Total units of this product sold
  totalRevenue: number;       // Total revenue generated by this product (from Sales)
  totalCost: number;          // Total estimated cost for the units of this product sold (from Entries)
  totalSalesRecords: number;      // Total number of sale records for this product
}

// Used for displaying the profitability table in RelatoriosPage, derived from ProductAnalysisData
export interface SalesProfitData extends ProductAnalysisData {
  totalProfit: number;     // Total estimated profit for this product (totalRevenue - totalCost)
  profitMargin: number;    // Profit margin percentage for this product ((totalProfit / totalRevenue) * 100)
}

// For new detailed report page
export interface DetailedSaleItem extends Sale {
  netRevenue: number;
  unitCost?: number; // Cost of one unit of the item sold
  totalCost?: number; // Total cost for the quantity of this item sold in this sale
  profit?: number; // Profit for this specific sale line item
  profitMargin?: number; // Profit margin for this specific sale line item
  costCalculated: boolean; // True if cost could be determined
}

export interface CustomerSalesReport {
  customerName: string;
  totalRevenue: number;
  totalCost: number;
  totalProfit: number;
  totalUnitsSold: number;
}

export interface ProductSalesReport {
  productId: string;
  productName: string;
  totalUnitsSold: number;
  totalRevenue: number;
  totalCost: number;
  totalProfit: number;
  avgProfitMargin?: number; // Optional: Average profit margin for this product
}

export interface DatePeriodSaleReport { // Used for Daily and Monthly
  period: string; // e.g., "2023-10-25" or "Out/23"
  totalRevenue: number;
  totalCost: number;
  totalProfit: number;
  sortableDate: string; // For sorting, e.g. "2023-10-25" or "2023-10"
}
    
